services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: api
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
